# https://docs.docker.com/compose/compose-file/
# docker-compose -f tutorial_mnist_distributed.yml up

---
version: '3'
services:
  master:
    image: tensorlayer/tensorlayer:latest
    entrypoint:
    - python
    - /tensorlayer/example/tutorial_mnist_distributed.py
    environment:
      CUDA_VISIBLE_DEVICES: ''
      TF_CONFIG: |-
        {
            "cluster": {
                "ps": [
                    "ps:3001"
                ],
                "worker": [
                    "master:3002",
                    "worker:3003"
                ]
            },
            "task": {
                "type": "worker",
                "index": 0
            }
        }
  worker:
    image: tensorlayer/tensorlayer:latest
    entrypoint:
    - python
    - /tensorlayer/example/tutorial_mnist_distributed.py
    environment:
      CUDA_VISIBLE_DEVICES: ''
      TF_CONFIG: |-
        {
            "cluster": {
                "ps": [
                    "ps:3001"
                ],
                "worker": [
                    "master:3002",
                    "worker:3003"
                ]
            },
            "task": {
                "type": "worker",
                "index": 1
            }
        }
  ps:
    image: tensorlayer/tensorlayer:latest
    entrypoint:
    - python
    - /tensorlayer/example/tutorial_mnist_distributed.py
    environment:
      CUDA_VISIBLE_DEVICES: ''
      TF_CONFIG: |-
        {
            "cluster": {
                "ps": [
                    "ps:3001"
                ],
                "worker": [
                    "master:3002",
                    "worker:3003"
                ]
            },
            "task": {
                "type": "ps",
                "index": 0
            }
        }
