# https://docs.readthedocs.io/en/latest/yaml-config.html

build:
  image: latest  # For python 3.6

formats:
    - epub
    - pdf

python:
    version: 3.6
    pip_install: true
    extra_requirements:
        - db
        - dev
        - doc
        - extra
        - test
